project:
  name: '@project.artifactId@'
  version: '@project.version@'
  description: '@project.description@'
info:
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: '@project.description@'
    version: '@project.version@'

application:
  title: ${project.name}
  version: ${project.version}

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  output:
    ansi:
      enabled: always

  banner:
    charset:  UTF-8
    location: classpath:/banner.txt

wiremock:
  url: http://localhost:8081/